"""empty message

Revision ID: 01821906851f
Revises: 24e2fd727b32
Create Date: 2021-01-01 19:21:57.290874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01821906851f'
down_revision = '24e2fd727b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'posts', ['post_id'], ['id'])
    op.drop_column('categories', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('category_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'posts', ['category_id'], ['id'])
    op.drop_column('categories', 'post_id')
    # ### end Alembic commands ###
