"""empty message

Revision ID: c45b284fce4d
Revises: 82a3fb0a62ca
Create Date: 2020-12-29 19:59:12.518020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45b284fce4d'
down_revision = '82a3fb0a62ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    op.alter_column('posts', 'body',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'body',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
